# Generated by Django 3.2 on 2021-04-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoAccion', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Acciones',
            },
        ),
        migrations.CreateModel(
            name='EstadoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstadoConsulta', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Estados de Consulta',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSector', models.CharField(max_length=100)),
                ('mail', models.EmailField(default='mesadeayuda@frm.utn.edu.ar', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='TipoSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoSolicitante', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Solicitante',
            },
        ),
        migrations.CreateModel(
            name='TipoProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionTipoProblema', models.CharField(max_length=100)),
                ('sectoresEncargados', models.ManyToManyField(blank=True, to='entities.Sector')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Problema',
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSolicitante', models.CharField(max_length=50)),
                ('apellidoSolitante', models.CharField(max_length=50)),
                ('emailSolicitante', models.EmailField(default='<django.db.models.fields.CharField>.<django.db.models.fields.CharField>@alumnos.frm.edu.ar', max_length=100)),
                ('legajo', models.IntegerField(blank=True, default='0')),
                ('tipoSolicitante', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entities.tiposolicitante')),
            ],
            options={
                'verbose_name_plural': 'Solicitantes',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asuntoConsulta', models.CharField(max_length=50)),
                ('descripcionConsulta', models.TextField()),
                ('fechayHoraConsulta', models.DateTimeField(auto_now=True)),
                ('nombreSolicitante', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidoSolitante', models.CharField(blank=True, max_length=50, null=True)),
                ('emailSolicitante', models.EmailField(blank=True, max_length=100)),
                ('estadoConsulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.estadoconsulta')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.solicitante')),
                ('tipoProblema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.tipoproblema')),
            ],
            options={
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
