# Generated by Django 3.2 on 2021-04-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_consulta_incidente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='apellidoSolitante',
        ),
        migrations.AddField(
            model_name='consulta',
            name='apellidoSolicitante',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
