# Generated by Django 3.2 on 2021-04-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_auto_20210420_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposolicitante',
            name='tiposProblema',
            field=models.ManyToManyField(blank=True, to='entities.TipoProblema'),
        ),
    ]
